//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect2Donate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAddress
    {
        public int AddressId { get; set; }
        public string Line1 { get; set; }
        public string Area { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public int UserId { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
